// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	. "github.com/Peyton232/todo/models"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// returns all users
	// (GET /users)
	FindUsers(w http.ResponseWriter, r *http.Request, params FindUsersParams)
	// Creates a new User
	// (POST /users)
	AddUser(w http.ResponseWriter, r *http.Request)
	// Update an existing user
	// (PUT /users)
	UpdateUser(w http.ResponseWriter, r *http.Request)
	// Deletes a user by ID
	// (DELETE /users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id int64)
	// Returns a user by ID
	// (GET /users/{id})
	FindUserByID(w http.ResponseWriter, r *http.Request, id int64)
	// get all Achievements
	// (GET /users/{id}/Achievements/)
	GetAchievements(w http.ResponseWriter, r *http.Request, id int64)
	// add new Achievements
	// (POST /users/{id}/Achievements/)
	AddAchievements(w http.ResponseWriter, r *http.Request, id int64)
	// update Achievement
	// (PUT /users/{id}/Achievements/)
	UpdateAchievements(w http.ResponseWriter, r *http.Request, id int64)
	// delete an Achievement by name
	// (DELETE /users/{id}/Achievements/{name})
	DeleteAchievement(w http.ResponseWriter, r *http.Request, id int64, name string)
	// get an Achievement by name
	// (GET /users/{id}/Achievements/{name})
	GetAchievement(w http.ResponseWriter, r *http.Request, id int64, name string)
	// get alerts
	// (GET /users/{id}/alerts)
	GetAlerts(w http.ResponseWriter, r *http.Request, id int64)
	// insert new alert
	// (POST /users/{id}/alerts)
	AddAlert(w http.ResponseWriter, r *http.Request, id int64)
	// update an alert
	// (PUT /users/{id}/alerts)
	UpdateAlert(w http.ResponseWriter, r *http.Request, id int64)
	// delete an Achievement by name
	// (DELETE /users/{id}/alerts/{name})
	DeleteAlert(w http.ResponseWriter, r *http.Request, id int64, name string)
	// delete an alert by name
	// (GET /users/{id}/alerts/{name})
	GetAlert(w http.ResponseWriter, r *http.Request, id int64, name string)
	// returns all of this users buckets
	// (GET /users/{id}/buckets)
	FindBuckets(w http.ResponseWriter, r *http.Request, id int32)
	// Creates a new Bucket
	// (POST /users/{id}/buckets)
	AddBucket(w http.ResponseWriter, r *http.Request, id int32)
	// Update an existing bucket
	// (PUT /users/{id}/buckets)
	UpdateBucket(w http.ResponseWriter, r *http.Request, id int32)
	// Deletes a bucket by name
	// (DELETE /users/{id}/buckets/{name})
	DeleteBucket(w http.ResponseWriter, r *http.Request, id int64, name string)
	// Returns a bucket by name
	// (GET /users/{id}/buckets/{name})
	FindBucketByName(w http.ResponseWriter, r *http.Request, id int32, name string)
	// get transactions
	// (GET /users/{id}/buckets/{name}/transactions)
	GetTransactions(w http.ResponseWriter, r *http.Request, id int64, name string)
	// Inserts a new transaction
	// (POST /users/{id}/buckets/{name}/transactions)
	InsertTransaction(w http.ResponseWriter, r *http.Request, id int64, name string)
	// update a transaction
	// (PUT /users/{id}/buckets/{name}/transactions)
	UpdateTransaction(w http.ResponseWriter, r *http.Request, id int64, name string)
	// delete a transaction
	// (DELETE /users/{id}/buckets/{name}/transactions/{timestamp})
	DeeleteTransaction(w http.ResponseWriter, r *http.Request, id int64, name string, timestamp string)
	// get a transaction by timestamp
	// (GET /users/{id}/buckets/{name}/transactions/{timestamp})
	GetTransaction(w http.ResponseWriter, r *http.Request, id int64, name string, timestamp string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// FindUsers operation middleware
func (siw *ServerInterfaceWrapper) FindUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FindUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindUsers(w, r, params)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AddUser operation middleware
func (siw *ServerInterfaceWrapper) AddUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddUser(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// FindUserByID operation middleware
func (siw *ServerInterfaceWrapper) FindUserByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindUserByID(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAchievements operation middleware
func (siw *ServerInterfaceWrapper) GetAchievements(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAchievements(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AddAchievements operation middleware
func (siw *ServerInterfaceWrapper) AddAchievements(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddAchievements(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateAchievements operation middleware
func (siw *ServerInterfaceWrapper) UpdateAchievements(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAchievements(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteAchievement operation middleware
func (siw *ServerInterfaceWrapper) DeleteAchievement(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAchievement(w, r, id, name)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAchievement operation middleware
func (siw *ServerInterfaceWrapper) GetAchievement(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAchievement(w, r, id, name)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAlerts operation middleware
func (siw *ServerInterfaceWrapper) GetAlerts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlerts(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AddAlert operation middleware
func (siw *ServerInterfaceWrapper) AddAlert(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddAlert(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateAlert operation middleware
func (siw *ServerInterfaceWrapper) UpdateAlert(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAlert(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteAlert operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlert(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAlert(w, r, id, name)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAlert operation middleware
func (siw *ServerInterfaceWrapper) GetAlert(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlert(w, r, id, name)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// FindBuckets operation middleware
func (siw *ServerInterfaceWrapper) FindBuckets(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindBuckets(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AddBucket operation middleware
func (siw *ServerInterfaceWrapper) AddBucket(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddBucket(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateBucket operation middleware
func (siw *ServerInterfaceWrapper) UpdateBucket(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBucket(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteBucket operation middleware
func (siw *ServerInterfaceWrapper) DeleteBucket(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBucket(w, r, id, name)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// FindBucketByName operation middleware
func (siw *ServerInterfaceWrapper) FindBucketByName(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindBucketByName(w, r, id, name)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetTransactions operation middleware
func (siw *ServerInterfaceWrapper) GetTransactions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTransactions(w, r, id, name)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// InsertTransaction operation middleware
func (siw *ServerInterfaceWrapper) InsertTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InsertTransaction(w, r, id, name)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateTransaction operation middleware
func (siw *ServerInterfaceWrapper) UpdateTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTransaction(w, r, id, name)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeeleteTransaction operation middleware
func (siw *ServerInterfaceWrapper) DeeleteTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "timestamp" -------------
	var timestamp string

	err = runtime.BindStyledParameterWithLocation("simple", false, "timestamp", runtime.ParamLocationPath, chi.URLParam(r, "timestamp"), &timestamp)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timestamp", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeeleteTransaction(w, r, id, name, timestamp)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetTransaction operation middleware
func (siw *ServerInterfaceWrapper) GetTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, chi.URLParam(r, "name"), &name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "timestamp" -------------
	var timestamp string

	err = runtime.BindStyledParameterWithLocation("simple", false, "timestamp", runtime.ParamLocationPath, chi.URLParam(r, "timestamp"), &timestamp)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timestamp", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTransaction(w, r, id, name, timestamp)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.FindUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.AddUser)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users", wrapper.UpdateUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.FindUserByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/Achievements/", wrapper.GetAchievements)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/{id}/Achievements/", wrapper.AddAchievements)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{id}/Achievements/", wrapper.UpdateAchievements)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}/Achievements/{name}", wrapper.DeleteAchievement)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/Achievements/{name}", wrapper.GetAchievement)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/alerts", wrapper.GetAlerts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/{id}/alerts", wrapper.AddAlert)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{id}/alerts", wrapper.UpdateAlert)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}/alerts/{name}", wrapper.DeleteAlert)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/alerts/{name}", wrapper.GetAlert)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/buckets", wrapper.FindBuckets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/{id}/buckets", wrapper.AddBucket)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{id}/buckets", wrapper.UpdateBucket)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}/buckets/{name}", wrapper.DeleteBucket)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/buckets/{name}", wrapper.FindBucketByName)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/buckets/{name}/transactions", wrapper.GetTransactions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/{id}/buckets/{name}/transactions", wrapper.InsertTransaction)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{id}/buckets/{name}/transactions", wrapper.UpdateTransaction)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}/buckets/{name}/transactions/{timestamp}", wrapper.DeeleteTransaction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/buckets/{name}/transactions/{timestamp}", wrapper.GetTransaction)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+ybX2/juBHAvwrB9qEFjDj3B33wU+O6VwRt7w7d5GmRB1oa2WwpUktS8RqBv3sxJGVJ",
	"FiUrt8bae/bTek16OJz5zXAYjd5oovJCSZDW0NkbNckacuY+PiRrDq+Qg7T430KrArTl4AaZH0zxcwom",
	"0bywXEk6o2tmiF1zQ5YAkuznTajdFkBndKmUACbpbkIlywEFhBFjNZcrHNCwYTp9yFXp185LYXkh4JeM",
	"zu7v7r/bC5NlvgRd/+TfYAxbxYS6KZ9KrlHnj37pl92EPgjQkf2lYEEzv3pHvXzsKtVEXGheJv+DmCX3",
	"u2zbMSm1BmmJHydcErsGsnRSiFEkY5pOxlhmzY1VeosrcAu5W/SPGjI6o3+Y1t6fBtdPnzSThiVOjd1e",
	"HtOabZtOa2v7M8uBqKyhY+3x2nDqFXQm1CYfwsbvsJoqo+ToUkSUEBydJsSW5GzFk5gGVlkmur90X1em",
	"dtvYazLGyDG4qrUmlYcRgr9rrXSXgUSlke24ycSNTWimdM4snVEu7Q/f11vj0sLKO7qBZUxQNTw5Am1Y",
	"sMnur1pl3Fu8rXjGJZMJZ+KfUm0EpCv4F7xCxMBrtSEmZ9ryRIBxmJQGNOEyupU1KwouwZgBcSul0oYg",
	"Q1KF24mJ49KUwvbIEvg1Ot3PMnHbKmnXYvuBCeZDqS2jJidXEpC/FEgBmrjfRSUejyPc11Fv7RNZM2xH",
	"J5km8UBsQ8So1NIS1vFRmTNJNLCULQUQ+FwIJhkOuvVaa3XiFD4XIE3EQDwEJzeESRQKRgJRmkhlo6nC",
	"8hyMZXkRifpq6KhCB0avZaLln9FPaGQh0FYfe87KvDpjR2Xh5ukbycIMj613SHOnXESOz3HjBYVTLCKJ",
	"R2qBZ8k/lUB4eoD0iGRW1ClnSJ8qMwVH/6SjUfW0LXxU8RxIhnPIn1LIWCksCZH956NO51jEVGq97F52",
	"O5dZMuUzuLQscREGOeMCLVNwCyz/q9mw1Qr0HVe0inr6wX9HHn59JE/A8k4wURzJlCZPKlVkXqYrsIQV",
	"BWoJOje/ZB9Av/IEha2tLWbTab3O1E2Z4lxu0YYUpXghdEJfQRu/yHd393f37mAuQLKC0xn9wX01oQWz",
	"a0fDFH3mPq0gkkH+A7bU0hAmhPOuIZlWuXO22RoL+JHZOk/jOc+SBIwhFg2CgeKSwmNKZ/QnLtNntx5q",
	"gI6ybvGPh8vm7DPPy5z4XIS+1eCyN7GKaKcTRe/QGf1Ugt7Wphc852gFT5A7xI7RuHtBEkyhpPER/f39",
	"feX0UB2zohA8cRuZ/tf4dFivMCq0XBrpBNauQ4YzY6WOB8eR/C6NhhTxRUpsZYn5NrGQEghzJtSUee7O",
	"RKoPUXBxrEyEmr9pYBYMYUTCpqoEHCQps0tm4I4sSq8/ztKAQtXG3SPaxDykDhjqYxWMnat0ezJTeJ/0",
	"+MAqwtIU/3G0W6WBNlOG1SXsvpCc36zcJQLS9nrFe1FGAMFEQJgng8mUlEXKLKChuUZGWAeEZzfjDCw8",
	"Bxa8ijcChgjwTvKVGzeWy5UvCXCWP2imbzzdeR4E2MhZ7r9HiAyXKxGOFcwZKVE+hzwuiClxb5F8sXA/",
	"D5gMHjGPCzxWqkgP6oQzBU/H+khxlUHb633ny19+HHe+/NjduNPEq5Fekk8Xe4d4T2zJ4wL1Gy4XDty2",
	"9+bjorcomG/d4DucloFN1l/NZ1cc14du9Qy0g7p5pTHT3oLSFbpCkObsDhL/AHswPpKKi4JhXxaOc07r",
	"StgtFA9d1rx2XiQ0UU/3loz4rasbBsF4SNPLA+P0tUgbhe7lsen6dpla1gXS16lRjqh68ZSi7TrY9ZWt",
	"5b6+aW47XqreOO1wGswXyrgbqu9ENZjv8JzoPYPfkJ4RxfYxnn0F2J5xXpwnhyvK8Hf1tpKRpcOzm/7F",
	"D/9I+HIDshfIKD5YHTor990RXF0wTFy7/rvhdsNtGwWnZu0gD9bPT6IImrXakDAnxl41cg23Dv/oaMR9",
	"Ayde8EXDuaz3esGlQfWx0nNTozeLMPD7LNWCn7tFmvPruW8RfdpdLnUdoo5fGuLkhevCdcN37qvBt8ff",
	"IVbxI/DUl4CLoLS3HqsC7OIrsW8Pt99W69e/iue+qti6IXXVSHkd+4r5RhPT0R6VMNd3qTBiCkh4xpMK",
	"ne6Tp3kQfgRA38OQfjF9Z2xA6evt+kZbUKo2Xt+VVDEysiUldCFnSodnWrH7wLxqED43GacvyCoWuh4I",
	"ljl388tRBS+/AaaOt5O2wFwllfM9lWdow+lX61tqxFlWu4gerqPvCY3OnBCJrd4cVzYd6c4ZR/BX7M/p",
	"Lf7qZDjQanKCMjDSDhSWvuiGoAqAI5eAunvkkBhGgvH66rL59mc/4YzJ7ux0XPmp2sVn+J4QUtm08caH",
	"GWxHak2M3FCf2uMXelHdv852Pgjf+eih9Sbi8QcQDTdd7GOIFkpjHka0X0tqo/fopj21ZlwNfKevLtu4",
	"DeJ15qch79D0EgPBc1tdg2z7fePBRySD4eBr2isNhxtpQ89A2pCNLwumb/tXPUc9IhnkcwFu1vUBOnnH",
	"i7eR9eq3bW9RcdK/qx+m3v5urOZMLK+bLhkqh2+A3wA/V8NPP7NOoAH9WkFZalG/R21VqpbuXem7xivV",
	"rOB097L7fwAAAP//Bdkn4jBHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
